// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://acxhhfwvxtkvxkvmfiep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFjeGhoZnd2eHRrdnhrdm1maWVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQyNDM0MjYsImV4cCI6MjA3OTgxOTQyNn0.pbNXGZAfetlZ_wKbXVVwZJgOGVge3nWINu_CnNgQezA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});